# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_title', models.CharField(max_length=250)),
                ('filter_description', models.CharField(max_length=500)),
                ('filter_logo', models.CharField(max_length=1000)),
                ('date_created', models.CharField(max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_title', models.CharField(max_length=250)),
                ('result_url', models.CharField(max_length=250)),
                ('result_image_url', models.CharField(max_length=250)),
                ('date_found', models.CharField(max_length=50)),
                ('time_left', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('is_favorite', models.BooleanField(default=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.Filter')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
