# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_auto_20170905_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_script',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
