# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0004_auto_20170905_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='filter_logo',
        ),
    ]
